---
title: "Checking outputs"
output: 
  html_document:
              toc: true
              toc_float: true
              toc_depth: 2
              collapsed: true
              smooth_scroll: true
              number_section: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
# Open packages we want
library(tidyverse)
library(here)
library(raster)
library(sf)
library(janitor)
library(rnaturalearth)
library(rnaturalearthdata)
library(knitr)
library(kableExtra)

# Raster templates
source(here("_spatial/template_raster.R"))

# File paths
raw   <- "/home/shares/food-systems/Food_footprint/_raw_data/"
prep  <- "/home/shares/food-systems/Food_footprint/dataprep/"
final <- "/home/shares/food-systems/Food_footprint/final_data/" 

# Extract world region borders
borders <- ne_countries(scale = "medium", returnclass = "sp")

# Extract MapSPAM crop category full names
SPAM_names <- vroom::vroom(here("crop_farm/data/SI_SPAM_crops_tbl.csv")) %>% 
  dplyr::select(1:2)
```

```{r, include = FALSE}
## Extract every crop name in the folder
crop_list <- list.files(path = file.path(final, 
                                         "_tif_version_raw", 
                                         fsep = ""),
                        pattern    = "crop",
                        full.names = TRUE)
  
crop_names <- str_extract(crop_list, "(?<=crop_).*(?=_)") %>% 
  unique()
length(crop_names)

undesirable_crops <- c("toba", "teas", "rcof", "acof")
```

```{r, include = FALSE}
# Broiler plots set-up
broiler_tifs <- list.files(path = file.path(final,
                                         "_tif_version_raw",
                                         fsep = ""),
                           pattern    = "broiler",
                           full.names = TRUE)

broiler_no_consumption_tifs <- broiler_tifs[-grep("consumption", broiler_tifs)]
broiler_consumption_tifs    <- broiler_tifs[ grep("consumption", broiler_tifs)]
```

```{r, include = FALSE}
# Broiler no consumption function
broiler_no_consumption_plot <- function(.x) {

  stressor   <- str_extract(.x, "(?<=broiler_).*(?=\\.tif)")
  raster_obj <- raster(.x)
  raster_obj[raster_obj == 0] <- NA
  
  cat('\n###',
      if_else(stressor == "ghg", 
              toupper(stressor), 
              Hmisc::capitalize(stressor)), 
      '\n')
  
  plot(raster_obj,
       legend = TRUE,
       legend.args = list(
       text = case_when(
         stressor == "water" ~ "m³",
         stressor == "disturbance" ~ "km²",
         stressor == "nutrient" ~ "tPO₄⁻",
         stressor == "ghg" ~ "CO₂"),
       cex  = 1,
       side = 3,
       line = 1),
       main = if_else(stressor == "ghg", 
                      toupper(stressor), 
                      Hmisc::capitalize(stressor)))

  plot(borders,
       border = "black",
       lwd    = 0.1,
       add    = TRUE)
  
  plot(log(raster_obj + 1),
       legend = TRUE,
       legend.args = list(
       text = case_when(
         stressor == "water" ~ "m³",
         stressor == "disturbance" ~ "km²",
         stressor == "nutrient" ~ "tPO₄⁻",
         stressor == "ghg" ~ "CO₂"),
       cex  = 1,
       side = 3,
       line = 1),
       main = paste("Logged",
                    if_else(stressor == "ghg", 
                            toupper(stressor), 
                            Hmisc::capitalize(stressor))))

  plot(borders,
       border = "black",
       lwd    = 0.1,
       add    = TRUE)
  
  cat('\n')
}
```

# Broiler Outputs 
## Stressors {.tabset .tabset-pills} 
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = "asis"}
map(.x = broiler_no_consumption_tifs,
    .f = broiler_no_consumption_plot)
```
{-}

```{r, include = FALSE}
broiler_plot_consumption <- function(.x) {

  raster_obj <- raster(.x)
  raster_obj[raster_obj == 0] <- NA
  
  crop_name <- str_extract(.x, "(?<=broiler_).*(?=\\_consumption.tif)")
  
  if (isTRUE(cellStats(raster_obj, stat = "sum", na.rm = TRUE) != 0)) {
  
  plot(raster_obj,
      legend = TRUE,
      legend.args = list(
      text = "Proportion",
      cex  = 1,
      side = 3,
      line = 1),
      main = ifelse(crop_name == "feedfish", 
                    "Feed fish", 
                    Hmisc::capitalize(SPAM_names$SPAM_full_name[
                      SPAM_names$SPAM_short_name == crop_name])))
  plot(borders,
       border = "black",
       lwd    = 0.1,
       add    = TRUE)
  
  } 
}

```

## Consumption
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = 'hide', fig.keep = 'all'}
map(.x = broiler_consumption_tifs, 
    .f = broiler_plot_consumption)
```

# Salmon Outputs
```{r, include = FALSE}
salmon_tifs <- list.files(path = file.path(final,
                                           "_tif_version_raw",
                                           fsep = ""),
                           pattern    = "salmon",
                           full.names = TRUE)
  
salmon_no_consumption_tifs <- salmon_tifs[-grep("consumption", salmon_tifs)]
salmon_consumption_tifs    <- salmon_tifs[ grep("consumption", salmon_tifs)]
```

```{r, include = FALSE}
salmon_no_consumption_plot <- function(.x) {

  stressor   <- str_extract(.x, "(?<=salmon_).*(?=\\.tif)")
  raster_obj <- raster(.x)
  raster_obj[raster_obj == 0] <- NA

  cat('\n###',
      if_else(stressor == "ghg", 
              toupper(stressor), 
              Hmisc::capitalize(stressor)), 
      '\n')

  cat('\n')

  plot(raster_obj,
      legend = TRUE,
      legend.args = list(
      text = case_when(
        stressor == "water" ~ "m³",
        stressor == "disturbance" ~ "km²",
        stressor == "nutrient" ~ "tPO₄⁻",
        stressor == "ghg" ~ "CO₂"),
      cex  = 1,
      side = 3,
      line = 1),
      main = if_else(stressor == "ghg", 
                     toupper(stressor), 
                     Hmisc::capitalize(stressor)))
  plot(borders,
       border = "black",
       lwd    = 0.1,
       add    = TRUE)
  
  plot(log(raster_obj + 1),
    legend = TRUE,
    legend.args = list(
    text = case_when(
      stressor == "water" ~ "m³",
      stressor == "disturbance" ~ "km²",
      stressor == "nutrient" ~ "tPO₄⁻",
      stressor == "ghg" ~ "CO₂"),
    cex  = 1,
    side = 3,
    line = 1),
    main = paste("Logged",
                 if_else(stressor == "ghg", 
                         toupper(stressor), 
                         Hmisc::capitalize(stressor)))
    )

  plot(borders,
       border = "black",
       lwd    = 0.1,
       add    = TRUE)
  
  cat('\n')
}
```

## Stressors {.tabset .tabset-pills} 
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = "asis"}
map(.x = salmon_no_consumption_tifs,
    .f = salmon_no_consumption_plot)
```
{-}

```{r, include = FALSE}
salmon_plot_consumption <- function(.x) {
  
  raster_obj <- raster(.x)
  raster_obj[raster_obj == 0] <- NA

  crop_name <- str_extract(.x, "(?<=salmon_).*(?=\\_consumption.tif)")
  
  if (isTRUE(cellStats(raster_obj, stat = "sum", na.rm = TRUE) != 0)) {
  
  plot(raster_obj,
      legend = TRUE,
      legend.args = list(
      text = "Proportion",
      cex  = 1,
      side = 3,
      line = 1),
      main = ifelse(crop_name == "feedfish", 
                    "Feed fish", 
                    Hmisc::capitalize(SPAM_names$SPAM_full_name[
                      SPAM_names$SPAM_short_name == crop_name])))

  plot(borders,
       border = "black",
       lwd    = 0.1,
       add    = TRUE)
  
  } 
}
```

## Consumption
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = 'hide', fig.keep = 'all'}
map(.x = salmon_consumption_tifs, 
    .f = salmon_plot_consumption)
```

```{r, include = FALSE}
crop_plots <- function(crop_tif) {
  
  stressor <- str_extract(crop_tif, "(?<=crop_...._).*(?=\\.tif)")
  raster_obj <- raster(crop_tif)
  raster_obj[raster_obj == 0] <- NA
  
  plot(raster_obj,
       legend = TRUE,
       legend.args = list(
       text = case_when(
         stressor == "water" ~ "m³",
         stressor == "disturbance" ~ "km²",
         stressor == "nutrient" ~ "tPO₄⁻",
         stressor == "ghg" ~ "CO₂"),
       cex  = 1,
       side = 3,
       line = 1),
       main = Hmisc::capitalize(word(gsub(pattern = "_", 
                                          replacement = " ", 
                                          x = str_extract(crop_tif, "(?<=crop_).*(?=\\.tif)")), 
                                     1)))
  plot(borders,
       border = "black",
       lwd    = 0.1,
       add    = TRUE)
  }

```

# Feed Crop Outputs 

## Stressors {.tabset .tabset-pills}

### GHG
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = 'hide', fig.keep = 'all'}
map(crop_list[grep("ghg", crop_list)],    
    crop_plots)
```

### Disturbance
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = 'hide',fig.keep = 'all'}
map(crop_list[grep("disturbance", crop_list)],    
    crop_plots)
```

### Water
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = 'hide',fig.keep = 'all'}
map(crop_list[grep("water", crop_list)],    
    crop_plots)
```

### Nutrient
```{r, echo = FALSE, message = FALSE, error = FALSE, fig.align = "centre", results = 'hide',fig.keep = 'all'}
map(crop_list[grep("nutrient", crop_list)],    
    crop_plots)
```
{-}