---
title: "crop residue burning check"
author: "Juliette"
date: "6/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(here)
library(countrycode)
library(doParallel)

prep <- "/home/shares/food-systems/Food_footprint/dataprep/"
raw <- "/home/shares/food-systems/Food_footprint/_raw_data/" 

rgns_tif <- raster("/home/shares/food-systems/Food_footprint/dataprep/spatial/master_rgns.tif")
food_crs <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"
rgn_info <- read_csv(here("_spatial/output/master_rgns.csv"))
rgns <- read_csv(here("_spatial/output/master_rgns.csv"))

```

Check the crop residue for maize, wheat, rice, and sugarcane


```{r}
fao_burn <- read_csv(file.path(raw, "FAO_data/v2020/FAOstat_cropburning_emissions/FAOSTAT_data_allcrops.csv")) %>% 
  mutate(fao_tonnes_co2eq = Value*1000) %>% 
  mutate(iso3c = countrycode(Area, origin="country.name", destination = "iso3c")) %>% 
  filter(Area != "China")%>% 
  mutate(SPAM_short_name = case_when(Item == "Maize" ~ "maiz",
                                     Item == "Rice, paddy" ~ "rice",
                                     Item == "Sugar cane" ~ "sugc",
                                     Item == "Wheat" ~ "whea")) %>% 
  dplyr::select(iso3c, SPAM_short_name, fao_tonnes_co2eq) 
```

```{r}

all_crops <- substring(list.files(file.path(prep, "crop_ghg/crop_residue_burning_ghg/co2eq_emitted")), first = 1, last = 4)

burn_crop_res <- data.frame(iso3c = NA, SPAM_short_name = NA, tonnes_co2eq = NA)

for(i in 1:length(all_crops)) {
  #crop_name = "maiz"

  ## prep the crop rasters
    crop_name <- all_crops[i]
    
      raster <- raster(list.files(file.path(prep, "crop_ghg/crop_residue_burning_ghg/co2eq_emitted"), pattern =  paste0(crop_name, sep = ""), full = TRUE))
    

    stack <- stack(raster, rgns_tif)
    df <- as.data.frame(stack, xy=TRUE)  
colnames(df) <- c("x", "y", "crop", "ID_0")
    
    summary <- df %>% 
      group_by(ID_0) %>% 
      dplyr::summarise(tonnes_co2eq = sum(crop, na.rm = TRUE)) %>% 
      ungroup() %>% 
      left_join(rgns, by = "ID_0") %>% 
      mutate(SPAM_short_name = crop_name) %>% 
      dplyr::select(iso3c, SPAM_short_name, tonnes_co2eq)
      
      burn_crop_res <- rbind(burn_crop_res, summary)
  }


```

Pull out the crops in our data that are in fao for number comparrisons
```{r}
crop_list <- c("maiz", "sugc", "rice", "whea")

burn_crop <- burn_crop_res %>% 
  filter(SPAM_short_name %in% crop_list) %>% 
  left_join(fao_burn, by = c("iso3c", "SPAM_short_name")) %>% 
  filter(!is.na(fao_tonnes_co2eq))

write_csv(burn_crop, here("_analysis/checking_data/JV_data/burn_crop.csv"))

total <- burn_crop_res %>% 
  filter(SPAM_short_name %in% crop_list) %>% 
  dplyr::summarise(total = sum(tonnes_co2eq, na.rm = TRUE))

total_no_rice <- burn_crop_res %>% 
  filter(SPAM_short_name %in% crop_list) %>% 
  filter(SPAM_short_name != "rice") %>% 
  dplyr::summarise(total = sum(tonnes_co2eq, na.rm = TRUE))

total_no_rice
total

global_summary <- burn_crop %>% 
  dplyr::summarise(our_total = sum(tonnes_co2eq, na.rm = TRUE),
                   fao_total = sum(fao_tonnes_co2eq, na.rm = TRUE))
```


Plot

```{r}
library(plotly)

plot <- ggplot(burn_crop, aes(x = tonnes_co2eq, y = fao_tonnes_co2eq, color = iso3c, shape = SPAM_short_name)) +
  geom_point() +
  xlab("Total CO2eq our maps")+
  ylab("Total CO2eq FAO reported")+
  theme_bw()+
    geom_abline(intercept=0, slope=1, color="red")
ggplotly(plot)

plot2 <- ggplot(burn_crop, aes(x = tonnes_co2eq, y = fao_tonnes_co2eq, color =SPAM_short_name)) +
  geom_point() +
  xlab("Total CO2eq our maps")+
  ylab("Total CO2eq FAO reported")+
  theme_bw()+
    geom_abline(intercept=0, slope=1, color="red")
plot2

```



FAO production data
```{r}
fao_prod_raw <- read_csv(file.path(raw, "FAO_data/v2020/FAO_crop_production/crops_FAOSTAT_data_5-22-2020.csv")) %>% 
  filter(Element == "Production")

fao_prod <- fao_prod_raw %>% 
  filter(Item %in% c("Wheat", "Rice, paddy", "Maize", "Sugar cane")) %>% 
  mutate(iso3c = countrycode(Area, origin="country.name", destination = "iso3c")) %>% 
  filter(Area != "China")%>% 
  mutate(SPAM_short_name = case_when(Item == "Maize" ~ "maiz",
                                     Item == "Rice, paddy" ~ "rice",
                                     Item == "Sugar cane" ~ "sugc",
                                     Item == "Wheat" ~ "whea")) %>% 
  dplyr::select(iso3c, SPAM_short_name, Value)

multiplier <- left_join(fao_burn, fao_prod, by = c("iso3c", "SPAM_short_name")) %>% 
  mutate(multiplier = fao_tonnes_co2eq/Value) %>% 
  filter(!is.na(multiplier))


mult_plot <- ggplot(multiplier, aes(y = fao_tonnes_co2eq, x = Value, color =SPAM_short_name)) +
  geom_point() +
  xlab("FAO Production")+
  ylab("Total CO2eq FAO reported")+
  theme_bw()
 # geom_abline(intercept=0, slope=1, color="red")
mult_plot

```














