---
title: "JV_irrigation_ghg"
author: "Juliette"
date: "6/8/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(countrycode)
library(tidyverse)
library(here)
library(raster)

prep <- "/home/shares/food-systems/Food_footprint/dataprep/"
raw <- "/home/shares/food-systems/Food_footprint/_raw_data/"

rgns_tif <- raster("/home/shares/food-systems/Food_footprint/dataprep/spatial/master_rgns.tif")
food_crs <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"
rgn_info <- read_csv(here("_spatial/output/master_rgns.csv"))
rgns <- read_csv(here("_spatial/output/master_rgns.csv"))

```

Read in FAO data
```{r}
fao_raw <- read_csv(file.path(raw, "FAO_data/v2020/fao_irrigation_energy.csv"))

fao <- fao_raw %>% 
  filter(Country != "China") %>% 
  dplyr::select(Country, Value) %>% 
  mutate(iso3c = countrycode(Country, origin="country.name", destination = "iso3c")) %>% 
  mutate(fao_co2eq = Value*1000) %>% 
  dplyr::select(iso3c, fao_co2eq)
```


```{r}

all_crops <- substring(list.files(file.path(prep, "crop_ghg/crop_irrigation_ghg/rasters")), first = 1, last = 4)

burn_crop_res <- data.frame(iso3c = NA, SPAM_short_name = NA, tonnes_co2eq = NA)

for(i in 1:length(all_crops)) {
  #crop_name = "maiz"

  ## prep the crop rasters
    crop_name <- all_crops[i]
    
      raster <- raster(list.files(file.path(prep, "crop_ghg/crop_irrigation_ghg/rasters"), pattern =  paste0(crop_name, sep = ""), full = TRUE))

    stack <- stack(raster, rgns_tif)
    df <- as.data.frame(stack, xy=TRUE)  
    colnames(df) <- c("x", "y", "crop", "ID_0")
    
    summary <- df %>% 
      group_by(ID_0) %>% 
      dplyr::summarise(tonnes_co2eq = sum(crop, na.rm = TRUE)) %>% 
      ungroup() %>% 
      left_join(rgns, by = "ID_0") %>% 
      mutate(SPAM_short_name = crop_name) %>% 
      dplyr::select(iso3c, SPAM_short_name, tonnes_co2eq)
      
      burn_crop_res <- rbind(burn_crop_res, summary)
  }


```


calculate sumamry totals
```{r}

irrigation <- burn_crop_res %>% 
  group_by(iso3c) %>% 
  dplyr::summarise(co2eq = sum(tonnes_co2eq, na.rm = TRUE))
  
```



Compare
```{r}

## combine
compare_irrigation <- left_join(fao, irrigation, by = "iso3c")

## global totals
global_totals <- compare_irrigation %>% 
  dplyr::summarise(fao_co2eq = sum(fao_co2eq),
                    co2eq = sum(co2eq))

##plot
ggplot(compare_irrigation, aes(x = co2eq, y = fao_co2eq)) +
  geom_point() +
  xlab("Our mapped CO2eq Values")+
  ylab("FAO CO2eq Values")+
  theme_bw()+
  geom_abline(intercept=0, slope=1, color="red")
```

Ours: 6,696,366 (when just looking at the countries that fao has. our real total is 7,438,175)
FAO: 46,990,511
Green Peace: 53,000,000 - 684,000,000







