---
title: "JV_machinery_crop_ghg"
author: "Juliette"
date: "6/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}

library(countrycode)

prep <- "/home/shares/food-systems/Food_footprint/dataprep/"
raw <- "/home/shares/food-systems/Food_footprint/_raw_data/"

rgns_tif <- raster("/home/shares/food-systems/Food_footprint/dataprep/spatial/master_rgns.tif")
food_crs <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"
rgn_info <- read_csv(here("_spatial/output/master_rgns.csv"))
rgns <- read_csv(here("_spatial/output/master_rgns.csv"))

```


```{r}

all_crops <- substring(list.files(file.path(prep, "crop_ghg/crop_machinery_ghg/total_em_crop")), first = 1, last = 4)

mach <- data.frame(iso3c = NA, SPAM_short_name = NA, tonnes_co2eq = NA)

for(i in 1:length(all_crops)) {
  #crop_name = "maiz"

  ## prep the crop rasters
    crop_name <- all_crops[i]
    
      raster <- raster(list.files(file.path(prep, "crop_ghg/crop_machinery_ghg/total_em_crop"), pattern =  paste0(crop_name, sep = ""), full = TRUE))

    stack <- stack(raster, rgns_tif)
    df <- as.data.frame(stack, xy=TRUE)  
    colnames(df) <- c("x", "y", "crop", "ID_0")
    
    summary <- df %>% 
      group_by(ID_0) %>% 
      dplyr::summarise(tonnes_co2eq = sum(crop, na.rm = TRUE)) %>% 
      ungroup() %>% 
      left_join(rgns, by = "ID_0") %>% 
      mutate(SPAM_short_name = crop_name) %>% 
      dplyr::select(iso3c, SPAM_short_name, tonnes_co2eq)
      
      mach <- rbind(mach, summary)
  }


```


```{r}

mach_em <- mach %>% 
  group_by(iso3c) %>% 
  dplyr::summarise(co2eq = sum(tonnes_co2eq, na.rm = TRUE))

total_sum <- mach_em %>% dplyr::summarise(sum = sum(co2eq))
  
```


Machinery Total:
27,830,108





