---
title: "JV_salmon_farm"
author: "Juliette"
date: "5/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(here)
library(countrycode)

prep <- "/home/shares/food-systems/Food_footprint/dataprep/"
final <- "/home/shares/food-systems/Food_footprint/final_data/" 
raw <- "/home/shares/food-systems/Food_footprint/_raw_data/" 

land_eez_rgns_tif <- raster("/home/shares/food-systems/Food_footprint/dataprep/spatial/land_eez_rgns.tif")
food_crs <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"
rgn_info <- read_csv(here("_spatial/output/master_rgns.csv"))

```

Salmon farm
1. Global/country sum head so salmon and compare it to country estimated values

look at the FAO aquaculture data 2019, is this the same as the 2020 i downloaded?
```{r}

our_salmon_raster <- read_csv(file.path(prep, "salmon_farm/salmon_farm.csv")) %>% 
  raster::rasterFromXYZ(crs = food_crs)

combine_rasts <- stack(our_salmon_raster, land_eez_rgns_tif)
salmon_df <- as.data.frame(combine_rasts, xy=TRUE)   

our_salmon <- salmon_df %>% 
  rename(ID_0 = land_eez_rgns) %>%
  group_by(ID_0) %>% 
  dplyr::summarise(our_maped_production = sum(tonnes_production, na.rm = TRUE))

our_salmon_rgn <- our_salmon %>%
  left_join(rgn_info, by="ID_0") %>% 
  filter(our_maped_production > 0)


## downloaded data from FAO FIGIS  
sal_aqua_raw <- read_csv(file.path(raw, "FAO_aquaculture/v_2020/FAO_FIGIS_aquacultrue.csv"))

sal_aqua <- sal_aqua_raw %>% 
  group_by(land_area) %>% 
  dplyr::summarise(fao_figis_production = sum(tons_salmon)) %>% 
  mutate(iso3c = countrycode(land_area, origin="country.name", destination = "iso3c")) 

compare <- sal_aqua %>%  
  left_join(our_salmon_rgn, by = "iso3c") %>% 
  mutate(fao_minus_ours  = fao_figis_production - our_maped_production,
         percent = fao_minus_ours/our_maped_production)

```

Looks kind of off...

Lets compare to the FAO data we downloaded from FishStatJ

```{r}
fao <-read_csv(here("salmon_farm/data/fao_mariculture_salmon.csv")) %>% 
  filter(year == 2016) %>% 
  rename(fao_fishJ_production = fao_tonnes_production)

compare_2 <- left_join(sal_aqua, our_salmon_rgn , by = "iso3c") %>% 
  left_join(fao, by = "iso3c") %>% 
  dplyr::select(iso3c, land_area, our_maped_production, fao_figis_production, fao_fishJ_production) %>% 
  mutate(fao_diff =fao_figis_production -fao_fishJ_production,
         figs_diff = our_maped_production-fao_figis_production,
         fishJ_diff = our_maped_production-fao_fishJ_production,
         figs_per_diff = abs(our_maped_production-fao_figis_production)/((our_maped_production+fao_figis_production)/2),
         fishJ_per_diff = abs(our_maped_production-fao_fishJ_production)/((our_maped_production+fao_fishJ_production)/2))

total_figs <- compare_2 %>% 
  filter(is.na(our_maped_production)) %>% 
  dplyr::summarise(total = sum(fao_figis_production))


10035.16/2384424
```















