---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Exploring data

## GHG
```{r}
library(raster)

broiler_ghg <- raster("/home/shares/food-systems/Food_footprint/final_data/_tif_version_raw/broiler_ghg.tif")
cellStats(broiler_ghg, "sum", na.rm=TRUE)


crops_ghg <- list.files("/home/shares/food-systems/Food_footprint/final_data/_tif_version_raw", pattern="crop", full=TRUE)
crops_ghg <- grep("ghg", crops_ghg, value=TRUE)

ghg_stack <- stack(crops_ghg)
N_sum <- sum(ghg_stack, na.rm=TRUE)
cellStats(N_sum, "sum", na.rm=TRUE)

broiler_crop_ghg <- raster("/home/shares/food-systems/Food_footprint/stressor_summary/feed_farm_system_stressor/raw/feed_crop_broiler_ghg.tif")
cellStats(broiler_crop_ghg, "sum", na.rm=TRUE)

chicken_location <- read_csv(file.path(prep, "chicken_farm/chickens_spatial_df_gf.csv"), col_types = "ddcccddddccc") 
protein_100g <- sum(chicken_location$tonnes_broiler_production, na.rm=TRUE) * 0.73 * 0.186 * 10000

co2_kg <- (95000000 + 121000000)*1000
co2_kg/protein_100g

```

## Water

```{r}
broiler_water <- raster("/home/shares/food-systems/Food_footprint/final_data/_tif_version_raw/broiler_water.tif")
cellStats(broiler_water, "sum", na.rm=TRUE)


crops_water <- list.files("/home/shares/food-systems/Food_footprint/final_data/_tif_version_raw", pattern="crop", full=TRUE)
crops_water <- grep("water", crops_ghg, value=TRUE)

ghg_stack <- stack(crops_ghg)
N_sum <- sum(ghg_stack, na.rm=TRUE)
cellStats(N_sum, "sum", na.rm=TRUE)

broiler_crop_ghg <- raster("/home/shares/food-systems/Food_footprint/stressor_summary/feed_farm_system_stressor/raw/feed_crop_broiler_ghg.tif")
cellStats(broiler_crop_ghg, "sum", na.rm=TRUE)

chicken_location <- read_csv(file.path(prep, "chicken_farm/chickens_spatial_df_gf.csv"), col_types = "ddcccddddccc") 
protein_100g <- sum(chicken_location$tonnes_broiler_production, na.rm=TRUE) * 0.73 * 0.186 * 10000

co2_kg <- (95000000 + 121000000)*1000
co2_kg/protein_100g
```

## Nutrients

```{r}
broiler_PO4 <- raster("/home/shares/food-systems/Food_footprint/final_data/_tif_version_raw/broiler_nutrient.tif")
cellStats(broiler_PO4, "sum", na.rm=TRUE)

broiler_crop_nutrient <- raster("/home/shares/food-systems/Food_footprint/stressor_summary/feed_farm_system_stressor/raw/feed_crop_broiler_nutrient.tif")
cellStats(broiler_crop_nutrient, "sum", na.rm=TRUE)

chicken_location <- read_csv(file.path(prep, "chicken_farm/chickens_spatial_df_gf.csv"), col_types = "ddcccddddccc") 
protein_100g <- sum(chicken_location$tonnes_broiler_production, na.rm=TRUE) * 0.73 * 0.186 * 10000

PO4eq_tonnes <- (3147811 + 3888632) * 1000000
PO4eq_tonnes/protein_100g
```
