---
title: "Untitled"
output: html_document
date: '2022-07-15'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(raster)
library(sf)
```

Determine tonnes going to each system.

```{r}

## total mapspam production

production <- read_csv(here("feed/data/MAPSPAMcrop_production.csv"))

# feed going to animal system
feed <- read_csv(here("feed/data/proportion_feed_per_country_system.csv")) %>%
  filter(animal_system %in% c("chickens_industrial_meat",
                              "salmon_aquaculture_meat")) %>%
  left_join(production, by=c("iso3c_producing", "SPAM_super")) %>%
  mutate(tonnes_feed = total_prop*tonnes_producing_crop) %>%
  mutate(system = ifelse(animal_system == "chickens_industrial_meat",
                         "feed_land_chickens_industrial_meat",
                         "feed_marine_salmon_aquaculture_meat")) %>%
  dplyr::select(iso3c=iso3c_producing, system, SPAM_super, total_prop, tonnes_producing_crop, tonnes_feed)

feed_summary <- feed %>%
  group_by(system, SPAM_super) %>%
  summarize(tonnes_feed = sum(tonnes_feed)) %>%
  filter(tonnes_feed >0) %>%
  arrange(system, -tonnes_feed)

```

## get the corresponding pressures

```{r}
source(here("_workflow/common.R"))
source(here("_workflow/common_spatial.R"))

rgns_ezz_land <- raster(file.path(prep, "spatial/land_eez_rgns.tif"))
rgns_ezz_land <-calc(rgns_ezz_land, fun = function(x){ifelse(is.na(x), 9999, x)})


file_list <- list.files("/home/shares/food-systems/Food_footprint/all_food_systems/analysis/raw_feed_combos", pattern = "chickens_industrial_meat|salmon_aquaculture_meat", full=TRUE)


summary_df <- data.frame(iso3c = c(),
                         country = c(),
                         filename = c(),
                         sum = c())


for(file in file_list){
  
#  file = file_list[1]
  
  file_name <- basename(file)
  file_name <- gsub(".tif", "", file_name)
  
  country_sum <- zonal(raster(file), rgns_ezz_land, fun="sum", progress="text", na.rm=TRUE) %>% 
    data.frame() %>%
    rename(ID_0 = zone) %>%
    left_join(food_rgns, by="ID_0")
  
  country_sum_clean <- country_sum %>%
  mutate(filename = file_name) %>% 
  select(-ID_0) %>% 
  rename(country = Country) %>% 
  relocate(sum, .after = last_col()) 
  
  summary_df <- rbind(summary_df, country_sum_clean)
  
  write_csv(summary_df, here("feed/chicken_salmon/feed_pressures.csv"))
}

```

Clean dataframe and rescale.
```{r}
rescale_values <- read_csv(here("../chicken_salmon_v2/_analysis/rescale_values.csv"))

summary_df <-  read_csv(here("feed/chicken_salmon/feed_pressures.csv"))

summary_df_clean <- summary_df %>%
    separate(filename, c("system", "other"), sep="_x_") %>%
   separate(other, c("origin", "SPAM_super", "source", "source2", "pressure")) %>%
  dplyr::select(-source, -source2, -origin)

crops <- summary_df_clean %>%
  dplyr::filter(SPAM_super %in% feed_summary$SPAM_super) %>%
  dplyr::group_by(iso3c, country, system, pressure) %>%
  dplyr::summarize(value = sum(sum, na.rm=TRUE)) %>%
  left_join(rescale_values, by="pressure") %>%
  mutate(rescale_value = value/global_total*0.25) # the 0.25 is to make sum to 1 vs. 4

crops %>%
  group_by(system) %>%
  summarize(total = sum(rescale_value))

crops_cpi <- crops %>%
  group_by(iso3c, country, system) %>%
  summarize(cpi = sum(rescale_value))

```

Join with tonnes production for feed.
```{r}
feed_crops <- feed %>%
  filter(SPAM_super %in% feed_summary$SPAM_super) %>%
  dplyr::group_by(iso3c, system) %>%
  dplyr::summarize(tonnes_feed = sum(tonnes_feed, na.rm=TRUE)) 

crops_cpi_production <- crops_cpi %>%
  left_join(feed_crops, by=c("iso3c", "system")) %>%
  filter(!(is.na(tonnes_feed))) %>%
  mutate(cpi_per_tonne = ifelse(cpi==0 & tonnes_feed==0, 0, cpi/tonnes_feed))

summary(crops_cpi_production)

write_csv(crops_cpi_production, here("feed/chicken_salmon/feed_cpi_per_tonne_crop.csv"))

```


fishoil/fishmeal
Determine tonnes going to each system.

```{r}
# fofm catch
total_tonnes_new_crs <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/fisheries/marine/ghg/watson_v5_emissions/catch_rasters/forage_fish_tonnes_new_crs_2017.tif")

prop_salmon <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/datalayers/marine_salmon_aquaculture_meat_x_marine_fofm_fisheries_meat.tif")
prop_chickens <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/datalayers/land_chickens_industrial_meat_x_marine_fofm_fisheries_meat.tif")


tonnes_salmon <- prop_salmon*total_tonnes_new_crs
tonnes_chicken <- prop_chickens*total_tonnes_new_crs

tonnes_fofm_catch <- zonal(stack(tonnes_salmon, tonnes_chicken), rgns_ezz_land, fun="sum", progress="text", na.rm=TRUE) %>% 
    data.frame() %>%
    rename(ID_0 = zone, feed_marine_salmon_aquaculture_meat = layer.1, feed_land_chickens_industrial_meat=layer.2) %>%
    left_join(food_rgns, by="ID_0") %>%
  pivot_longer(cols=c(feed_marine_salmon_aquaculture_meat, feed_land_chickens_industrial_meat), names_to=c("system"), values_to = "tonnes_feed") %>%
  select(iso3c, system, tonnes_feed)

```

Combine fofm with pressures
```{r}
rescale_values <- read_csv(here("../chicken_salmon_v2/_analysis/rescale_values.csv"))

summary_df <-  read_csv(here("feed/chicken_salmon/feed_pressures.csv"))

summary_df_clean <- summary_df %>%
    separate(filename, c("system", "other"), sep="_x_") %>%
   separate(other, c("origin", "fofm", "source", "source2", "pressure")) %>%
  dplyr::select(-source, -source2, -origin) %>%
  filter(fofm == "fofm")

fofm <- summary_df_clean %>%
  dplyr::group_by(iso3c, country, system, fofm, pressure) %>%
  dplyr::summarize(value = sum(sum, na.rm=TRUE)) %>%
  left_join(rescale_values, by="pressure") %>%
  mutate(rescale_value = value/global_total*0.25) # the 0.25 is to make sum to 1 vs. 4

fofm %>%
  group_by(system) %>%
  summarize(total = sum(rescale_value))

fofm_cpi <- fofm %>%
  group_by(iso3c, country, system, fofm) %>%
  summarize(cpi = sum(rescale_value))

```

Join with tonnes production for feed.
```{r}

fofm_cpi_production <- fofm_cpi %>%
  left_join(tonnes_fofm_catch, by=c("iso3c", "system")) %>%
  filter(!(is.na(tonnes_feed))) %>%
  mutate(cpi_per_tonne = ifelse(cpi==0 & tonnes_feed==0, 0, cpi/tonnes_feed))

summary(fofm_cpi_production)

write_csv(fofm_cpi_production, here("feed/chicken_salmon/feed_cpi_per_tonne_fofm.csv"))

```
