---
title: "Circle barplots"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(tidyverse)
library(ggplot2)
library(here)

un_geopolitical <- read_csv(here("_spatial/output/UNSD_Methodology.csv")) %>%
  dplyr::select(iso3c, georegion=Region_Name)

rgn_names <- read_csv(here("_spatial/output/master_rgns.csv")) %>%
  rename(land_area_km2 = area_km2)
eez_rgns <- read_csv(here("_spatial/output/eez_rgns.csv")) %>%
  rename(eez_area_km2 = area_km2)

rescaling_values <- read_csv(here("_analysis/rescale_values.csv")) %>%
  rename(stressor=pressure)


```


# data
```{r}


pressures <- read_csv(here("_analysis/output_data/sum_pressures_country.csv"))  %>%
    filter(!is.na(Country)) %>% ## Antarctica
  left_join(rescaling_values, by="stressor") %>%
  rowwise() %>%
  mutate(prop_of_global = value/global_total) %>%
   group_by(iso3c, Country, source, subsource, animal_system, location) %>%
  summarize(country_farm_feed_chi = sum(prop_of_global, na.rm=TRUE)) %>%
  left_join(rgn_names) %>%
  left_join(eez_rgns) %>%
  rowwise() %>%
  mutate(avg_cum_stress_km2_1e_6= ifelse(location=="marine", 
                          country_farm_feed_chi/eez_area_km2*1000000,
                          country_farm_feed_chi/land_area_km2*1000000)) %>%
  ungroup() %>%
   mutate(prop_of_global = ifelse(is.na(avg_cum_stress_km2_1e_6), 0, avg_cum_stress_km2_1e_6)) %>%

    mutate(source = ifelse(is.na(subsource), paste(animal_system, source, sep="-"), 
                         paste(animal_system, source, subsource, sep="-"))) %>%
left_join(un_geopolitical, by="iso3c") %>%
  select(Country, iso3c, location, source, avg_cum_stress_km2_1e_6, georegion)
  

## get georegion ranks
chi <- pressures %>%
  group_by(georegion, Country, iso3c) %>%
  summarize(chi = sum(avg_cum_stress_km2_1e_6, na.rm=TRUE)) %>%
  arrange(-chi)

rank_georgn <- chi %>%
  group_by(georegion) %>%
  summarize(mean_chi = mean(chi),
            count = length(chi)) %>%
  ungroup() %>%
  data.frame() %>%
  arrange(mean_chi)

rank_georgn$georegion <- factor(rank_georgn$georegion, 
                                         levels=unique(rank_georgn$georegion))

chi$georegion <- factor(chi$georegion, 
                                         levels=unique(rank_georgn$georegion))
### Organize the chi data and add a few extra variables to help plotting
# Including empty spaces to add a y-axes
rank_rgn <- chi %>%
  arrange(georegion, chi) %>%
  data.frame()


# modify region names to be shorter
rank_rgn <- rank_rgn %>%
  mutate(rgn_name_short = Country, 
         rgn_name_short = gsub("Islands", "Isl", rgn_name_short),
         rgn_name_short = gsub("Island", "Isl", rgn_name_short),
         rgn_name_short = gsub("Democratic", "Dem", rgn_name_short),
         rgn_name_short = gsub("Republic", "Rep", rgn_name_short),
         rgn_name_short = gsub("South", "S", rgn_name_short),
         rgn_name_short = gsub("American", "Am", rgn_name_short),
         rgn_name_short = gsub("the United States", "US", rgn_name_short),
         rgn_name_short = gsub("Territory", "Terr", rgn_name_short),
         rgn_name_short = gsub("Saint", "St", rgn_name_short),
         rgn_name_short = gsub(" and ", " & ", rgn_name_short),
         rgn_name_short = gsub("Republique", "Rep", rgn_name_short),
         rgn_name_short = gsub("Dem Rep of the", "Dem Rep of", rgn_name_short),
         rgn_name_short = gsub("Georgia and the", "Georgia and", rgn_name_short),
         rgn_name_short = gsub("St Vincent and the", "St Vincent and", rgn_name_short),
         rgn_name_short = gsub("Howland Isl & Baker Isl", "Howland & Baker Isl", rgn_name_short),
         rgn_name_short = gsub("Northern", "N", rgn_name_short), 
         rgn_name_short = gsub("Reunion", "Reunion", rgn_name_short))

```
## adjust data for particular plotting needs
  - determine what will be plotted inside the circle
  - subset the high values to be placed inside a different plot

## Stuff for both plots
```{r}

source_name <- data.frame(source = c("chickens-farm-land", "chickens-feedcrop-land", "salmon-feedcrop-marine", 
                                         "salmon-farm-marine", "chickens-feedfofm-land", "salmon-feedfofm-marine"),
                            source_name = c("Broiler: farm", "Broiler: feed, crops", "Salmon: feed, crops",
                                              "Salmon: farm", "Broiler: feed, fish", "Salmon: feed, fish"))

myPalette <- c("#D7A374", "#609DA4", "#1D6060",  # darkbrown, lightergreen, darkergreen
               "#6F4C41", "#CCEAF4", "#005AB8")    # tan, lighterblue, darkerblue   

cutoff_value <- 1
```


#### Circle part
```{r}
#explore chi values
pressures %>%
  group_by(Country, iso3c) %>%
  summarize(chi = sum(avg_cum_stress_km2_1e_6, na.rm=TRUE)) %>%
  arrange(chi) %>% data.frame()
filter(pressures, iso3c=="MCO")
#filter to include only countries in circle
pressures_adj_circle <- pressures %>%
  group_by(Country, iso3c) %>%
  mutate(chi = sum(avg_cum_stress_km2_1e_6, na.rm=TRUE)) %>%
  mutate(avg_cum_stress_km2_1e_6 = ifelse(location=="marine", avg_cum_stress_km2_1e_6*(-1), avg_cum_stress_km2_1e_6)) %>%
  ungroup() %>%
  arrange(chi) %>%
  filter(chi<=cutoff_value)

highest_country <- pressures_adj_circle[dim(pressures_adj_circle)[1], "iso3c"]
pressures_highest_country <- filter(pressures_adj_circle, iso3c %in% highest_country$iso3c) #used below



# adjust the rank_rgn-adjust dataframe to match above
rank_rgn_adj <- rank_rgn %>%
  filter(iso3c %in% pressures_adj_circle$iso3c) 
  

# # add empty space to create space in the circleplot for axes
 empty_bar <- 6
 to_add <- data.frame(matrix(NA, empty_bar, ncol(rank_rgn_adj)) )
 colnames(to_add) = colnames(rank_rgn_adj)
 to_add$Country <- as.character(1:empty_bar)
 rank_rgn_adj  <- rbind(to_add, rank_rgn_adj)


# some code to orient the country labels
sequence_length = length(unique(rank_rgn_adj$Country))
first_sequence = c(1:(sequence_length%/%2)) 
second_sequence = c((sequence_length%/%2+1):sequence_length) 
first_angles = c(90 - 180/length(first_sequence) * first_sequence)
second_angles = c(-90 - 180/length(second_sequence) * second_sequence)

rank_rgn_adj$angle <- c(first_angles, second_angles)
rank_rgn_adj$hjust <- c(rep(0, length(first_sequence)), 
                    rep(1, length(second_sequence)))

# color for region labels
rank_rgn_adj <- rank_rgn_adj %>%
  mutate(Country = factor(Country, unique(Country))) %>%
  mutate(georegion = factor(georegion, unique(georegion))) %>%
  mutate(color = "black") %>%
  mutate(color = ifelse(is.na(chi), "white", color)) %>%
  mutate(color = ifelse(iso3c %in% highest_country$iso3c, "red", color))

# get dataframe for georegion shift locations
rgn_shift <- rank_rgn_adj %>%
  mutate(georegion = ifelse(is.na(georegion), "tmp", georegion)) %>%
  mutate(georegion = as.factor(georegion)) %>%
  mutate(region_shift = as.numeric(georegion) - lag(as.numeric(georegion)), default=first(as.numeric(georegion)))

rgn_shift <- which(rgn_shift$region_shift > 0)
rgn_shift <- c(1, rgn_shift) -0.05
rgn_shift <- data.frame(rgn_shift_x=rgn_shift,
                         georegion = rank_georgn$georegion,
                         name_x= c(15, 60, 115, 150, 200), # 140
                         name_y=c(0.55, 0.55, 0.55, 0.55, 0.55))
rgn_shift <- rgn_shift %>%
   mutate(georegion = as.character(georegion))

# ## add some blanks rows to match the master region list
  to_add <-  data.frame( matrix(NA, empty_bar*nlevels(as.factor(pressures_adj_circle$source)), ncol(pressures_adj_circle)) )
  colnames(to_add) <- colnames(pressures_adj_circle)
  to_add$source <- rep(levels(as.factor(pressures_adj_circle$source)), each=empty_bar)
  to_add$avg_cum_stress_km2_1e_6<-  0
  to_add$Country <- as.character(rep(1:empty_bar, nlevels(as.factor(pressures_adj_circle$source)))) 
  pressures_adj_circle <- rbind(to_add, pressures_adj_circle, to_add)

pressures_adj_circle %>%
  group_by(source) %>%
  summarize(mean = mean(avg_cum_stress_km2_1e_6, na.rm=TRUE)) %>%
  arrange(mean)

pressures_adj_circle <- pressures_adj_circle %>%
  left_join(source_name, by = "source")


pressures_adj_circle$source_name <- factor(pressures_adj_circle$source_name, levels=rev(source_name$source_name))
pressures_adj_circle$Country <- factor(pressures_adj_circle$Country, levels=unique(rank_rgn_adj$Country))
pressures_adj_circle$georegion <- factor(pressures_adj_circle$georegion, 
                                         levels=unique(rank_georgn$georegion))

## some theme stuff to make the circle plot look nice

circle_theme <- theme(axis.line=element_blank(),
                      axis.text.y=element_blank(),
                      axis.ticks=element_blank(),
                      axis.title.x=element_blank(),
                      axis.title.y=element_blank(),
                      legend.position="none",
                      panel.background=element_blank(),
                      panel.border=element_blank(),
                      panel.grid.major=element_blank(),
                      panel.grid.minor=element_blank(),
                      plot.background=element_blank(),
                      axis.text.x = element_blank())



p <- ggplot(data=pressures_adj_circle, aes(x=Country, y=avg_cum_stress_km2_1e_6, fill=source)) + 
  
  geom_bar(stat="identity", aes(fill=source_name)) +
  
  # ## this adjust the inner circle size (ymin) and outer circle size (ymax), which can be expanded to include names
   geom_errorbar(aes(
       x     = 1, 
       ymin  = -0.3,   
       ymax  = 1.10), 
       alpha = 0) +

      # Country name text placement
     geom_text(
       data = rank_rgn_adj,  
       aes(x     = Country,  
           y     = max(pressures_adj_circle$chi, na.rm=TRUE), 
           label = rgn_name_short, 
           angle = angle, 
           hjust = hjust),
       inherit.aes = FALSE, 
       fontface = "bold", 
       alpha = 0.9, 
       size = 4, 
       color = rank_rgn_adj$color) +
    # 
   # georegion names
    geom_text(
      data=rgn_shift, 
      aes(x=name_x, 
          y=name_y, 
          label=georegion), 
      inherit.aes=FALSE, size=7) +
  #  
  # # # Scale bar circles
  # ## This adds the 0 line
      geom_segment(
        x = 0, 
         y = 0, 
         xend = dim(rank_rgn_adj)[1]+1, 
         yend = 0, 
         fill = NULL,
        alpha = 1, color = "black", size = 0.3) +
  #    
  #  # Scale bar annotation, this adds the y-axis numbers
      annotate(
        "text", 
        x     = c(3, 3, 3), 
        y     = c(-0.25, 0, 0.50),
        label = c(-0.25, 0, 0.50), 
        color = "darkgray", angle = -4, size = 6) +
  #     
  scale_colour_identity() +
  scale_fill_manual(values=myPalette, limits=c("Broiler: farm", "Broiler: feed, crops", "Salmon: feed, crops",
                                              "Salmon: farm", "Broiler: feed, fish", "Salmon: feed, fish")) +
  coord_polar() +

 circle_theme

#p
ggsave(here('_analysis/figures/circular_plots/feed_farm_marine_land.png'), height=18, width=18, units=c("in"), bg="transparent")


```


#### Bar part
```{r}


pressures_adj_bar <- pressures %>%
  group_by(Country, iso3c) %>%
  mutate(chi = sum(avg_cum_stress_km2_1e_6, na.rm=TRUE)) %>%
  mutate(avg_cum_stress_km2_1e_6 = ifelse(location=="marine", avg_cum_stress_km2_1e_6*(-1), avg_cum_stress_km2_1e_6)) %>%
  ungroup() %>%
  filter(chi>cutoff_value) %>%
  rbind(pressures_highest_country) %>%
  arrange(chi)



rank_rgn_adj_bar <- rank_rgn %>%
  filter(iso3c %in% pressures_adj_bar$iso3c)


# color for region labels
rank_rgn_adj_bar <- rank_rgn_adj_bar %>%
  mutate(Country = factor(Country, unique(Country))) %>%
  mutate(georegion = factor(georegion, unique(georegion))) %>%
  mutate(color = "black") %>%
  mutate(color = ifelse(is.na(chi), "white", color))%>%
  mutate(color = ifelse(iso3c %in% highest_country$iso3c, "red", color)) %>%
  arrange(-chi)


pressures_adj_bar <- pressures_adj_bar %>%
  left_join(source_name, by = "source")


pressures_adj_bar$source_name <- factor(pressures_adj_bar$source_name, levels=rev(source_name$source_name))
pressures_adj_bar$Country <- factor(pressures_adj_bar$Country, levels=unique(rank_rgn_adj_bar$Country))


## some theme stuff to make the plot look nice

bar_theme <- theme(axis.line=element_blank(),
                      axis.text.y=element_blank(),
                      axis.ticks=element_blank(),
              #        axis.title.x=element_blank(),
                      axis.title.y=element_blank(),
              #        legend.position="none",
                      panel.background=element_blank(),
                      panel.border=element_blank(),
                      panel.grid.major=element_blank(),
                      panel.grid.minor=element_blank(),
                      plot.background=element_blank(),
                      legend.title = element_blank(),
                      axis.text.x = element_blank()
              )



p <- ggplot(data=pressures_adj_bar, aes(x=Country, y=avg_cum_stress_km2_1e_6, fill=source_name)) + 
  
  geom_bar(stat="identity") +
  ylab(bquote("cumulative pressures per" ~km^2~"(x 1e6)")) +
   
  # ## this adjust the plot dimensions, which can be expanded to include names
    geom_errorbar(aes(
        x     = 1, 
        ymin  = -1,   
        ymax  = 2), 
        alpha = 0) +

   geom_errorbar(aes(
       y     = -2,
       xmin  = -1,
       xmax  = -1),
       alpha = 0) +
  
      # Country name text placement
    geom_text(
      data = rank_rgn_adj_bar,
      aes(y = -1,
          x = 1:length(rank_rgn_adj_bar$Country),
          label = rgn_name_short),
      inherit.aes = FALSE,
  #    fontface = "bold",
      alpha = 0.9,
      size = 3,
      color = rank_rgn_adj_bar$color,
      hjust = 1) +

   # Scale bar annotation, this adds the y-axis numbers
      annotate(
        "text",
        x     = c(-0.025, -0.025, -0.025),
        y     = c(0, 0.5, 1),
        label = c(0, 0.5, 1),
        color = "darkgray", size = 3) +

  scale_colour_identity() +
  scale_fill_manual(values=myPalette, limits=c("Broiler: farm", "Broiler: feed, crops", "Salmon: feed, crops",
                                              "Salmon: farm", "Broiler: feed, fish", "Salmon: feed, fish")) +
  coord_flip() +

bar_theme

#p
ggsave(here('_analysis/figures/circular_plots/feed_farm_marine_land_barplot.png'), height=6, width=5, units=c("in"),
       bg="transparent")


```