---
title: "Untitled"
author: "Caitie"
date: '2022-04-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(patchwork)
library(tidyverse)
library(ggrepel)
library(ggpmisc)
library(ggforce)
```

# Data
```{r}
chick_dat<-read.csv(here("_analysis/output_data/Broiler_farm_feed_cpi.csv"))
chick_prod<-read.csv("/home/shares/food-systems/Food_footprint/chicken_salmon/production/broiler_production.csv") %>% 
  dplyr::select(iso3c, Country, broiler_slaughter_wt_tonnes)

chick_all<-full_join(chick_dat, chick_prod) %>% 
  mutate(eff = country_farm_feed_chi/broiler_slaughter_wt_tonnes)
```


```{r}
salmon_dat<-read.csv(here("_analysis/output_data/Salmon_farm_feed_cpi.csv"))
salmon_prod<-read.csv("/home/shares/food-systems/Food_footprint/chicken_salmon/production/salmon_production.csv") %>% 
  dplyr::select(iso3c, country, fao_tonnes_production) %>% 
  rename(Country = country)

salmon_all<-full_join(salmon_dat, salmon_prod) %>% 
  mutate(eff = country_farm_feed_chi/fao_tonnes_production)
```


Chicken farm CPI vs production


```{r}
chick_all_farm<-chick_all %>% 
  filter(source2 == "farm") %>% 
  mutate(broiler_cpi_prod_lab = ifelse(broiler_slaughter_wt_tonnes>240000000 | country_farm_feed_chi > 0.02, as.character(Country), NA))

cp1<-ggplot(chick_all_farm, aes(x = broiler_slaughter_wt_tonnes/1000000, y = country_farm_feed_chi, label = Country)) +
  #annotation_custom(chicken_png, xmin = 0, xmax = 2.5, ymin = 0.65, ymax=0.75) +
  geom_point() +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel(max.overlaps = 40) + 
  theme_bw() +
  xlab("Slaughter weight (million tonnes)") +
  ylab("") #+
  #scale_x_log10() +
  #scale_y_log10()

cp1

```
```{r}
cp3<-cp1+
facet_zoom(xlim = c(0, 2.5),
           ylim = c(0,0.025), 
           horizontal = T, 
           zoom.size = 1)

cp3
```
```{r}
ggsave(here("_analysis/figures/Chicken_direct_prod_inset1.png"), dpi = 300, height = 3, width = 10)

```



```{r}
sub<-chick_all_farm %>% 
  filter(broiler_slaughter_wt_tonnes<2500000)

cp2<-ggplot(sub, aes(x = broiler_slaughter_wt_tonnes/1000000, y = country_farm_feed_chi, label = Country)) +
  #annotation_custom(chicken_png, xmin = 0, xmax = 2.5, ymin = 0.65, ymax=0.75) +
  geom_point() +
  #xlim(c(0,2.5)) +
  coord_cartesian(xlim = c(0, 2.5)) +
  scale_x_continuous(breaks = seq(from = 0, to = 2.5, by = 0.5)) +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel(max.overlaps = 50) + 
  theme_bw() +
  xlab("Slaughter weight (million tonnes)") +
  ylab("") +
  ylim(c(0,0.025))

cp2
```








 Salmon CPI vs production
 
```{r}
salmon_all_farm<- salmon_all %>% 
  filter(source2 == "farm")

sp1<-ggplot(salmon_all_farm, aes(x = fao_tonnes_production/10000, y = country_farm_feed_chi, label = Country)) +
  #annotation_custom(salmon_png, xmin = 0, xmax = 20, ymin = 0.035, ymax=0.045) +
  geom_point() +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel() + 
  theme_bw() +
  xlab("Slaughter weight (ten thounsand tonnes)") +
  ylab("") 

sp1
```
```{r}
ggsave(here("_analysis/figures/Salmon_direct_prod.png"), dpi = 300, height = 3, width = 5)

```






