---
title: "Untitled"
author: "Caitie"
date: '2022-04-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(patchwork)
library(tidyverse)
library(ggrepel)
library(ggpmisc)
library(ggforce)
library(raster)
library(here)

#devtools::install_github("thomasp85/ggforce")
```


# Data
# Extract cells within each country

```{r}
rgns <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/spatial/land_eez_rgns.tif")
#plot(rgns)

rgn_names <- read_csv("/home/shares/food-systems/Food_footprint/chicken_salmon/_spatial/master_rgns.csv") %>%
  rename(land_area_km2 = area_km2)

broiler_cpi<-raster("/home/shares/food-systems/Food_footprint/chicken_salmon/rescaled_cumulative_pressure/chickens_cumulative_stress.tif")

salmon_cpi<-raster("/home/shares/food-systems/Food_footprint/chicken_salmon/rescaled_cumulative_pressure/salmon_cumulative_stress.tif")
```

```{r}
iso3_broiler_cpi<-read.csv(here("_analysis/figures/Country_results/Broiler_country_cpi.csv"))

iso3_salmon_cpi<-read.csv(here("_analysis/figures/Country_results/Salmon_country_cpi.csv"))
```

```{r}
broiler_prod<-read.csv("/home/shares/food-systems/Food_footprint/chicken_salmon/production/broiler_production.csv")
salmon_prod<-read.csv("/home/shares/food-systems/Food_footprint/chicken_salmon/production/salmon_production.csv")
```

```{r}
rgns_proj<-projectRaster(rgns, crs = broiler_cpi)
rgns_rs<-resample(rgns_proj, broiler_cpi)

rgn_df<-tabularaster::as_tibble(rgns_rs) %>% 
  rename(ID_0 = cellvalue)

rgn_names_df<-full_join(rgn_names, rgn_df) %>% 
  group_by(iso3c, Country) %>% 
  mutate(ncells = length(unique(cellindex)))

broiler_cpi_df<-as_tibble(broiler_cpi) %>% 
  mutate(cellvalue = cellvalue/1000000) %>% 
  rename(broiler_cpi = cellvalue)

salmon_cpi_df<-as_tibble(salmon_cpi) %>% 
  mutate(cellvalue = cellvalue/1000000) %>% 
  rename(salmon_cpi = cellvalue)


iso3_cpi<-full_join(rgn_names_df, broiler_cpi_df) %>% 
  full_join(., salmon_cpi_df) 

bottom_5_perc<-iso3_cpi %>% 
  group_by(iso3c, Country) %>% 
  summarise(broiler_quant_5 = quantile(broiler_cpi, probs = 0.05, na.rm = T),
         salmon_quant_5 = quantile(salmon_cpi, probs = 0.05, na.rm = T))

rm_5<-full_join(iso3_cpi, bottom_5_perc) %>% 
  mutate(broiler_cpi2 = ifelse(broiler_cpi<=broiler_quant_5, NA, as.numeric(broiler_cpi)),
         salmon_cpi2 = ifelse(salmon_cpi<=salmon_quant_5, NA, as.numeric(salmon_cpi)))

#broiler_prod<-broiler_prod %>% 
#  rename(broiler_kcal = kcal,
#         broiler_protein_tonnes = protein_tonnes)

#salmon_prod<-salmon_prod %>% 
#  rename(salmon_kcal = kcal,
#         salmon_protein_tonnes = protein_tonnes) %>% 
#  mutate(country = ifelse(country == "United States of America", "United States", country))
  
test<-rm_5 %>% 
  group_by(iso3c, ncells) %>% 
  summarise(broiler_cells = length(which(broiler_cpi2>0)),
         salmon_cells = length(which(salmon_cpi2>0))) %>% 
  mutate(prop_broiler = broiler_cells/ncells) %>% 
  filter(!is.na(iso3c) == T) %>% 
  full_join(., iso3_salmon_cpi) %>% 
  rename(salmon_cpi = country_farm_feed_chi) %>% 
  dplyr::select(-animal_system, -variance_chi) %>% 
  full_join(., iso3_broiler_cpi) %>% 
  rename(chicken_cpi = country_farm_feed_chi) %>% 
  dplyr::select(-animal_system) %>% 
  mutate(broiler_cpi_cell = chicken_cpi/broiler_cells,
         salmon_cpi_cell = salmon_cpi/salmon_cells) %>% 
  full_join(., broiler_prod) %>% 
  full_join(., salmon_prod, by = c("Country" = "country", "iso3c")) %>% 
  mutate(prop_salmon = salmon_cells/ncells)

cells_iso3_cpi<- iso3_cpi %>% 
  group_by(iso3c, Country, ncells) %>% 
  summarise(broiler_cells = length(which(broiler_cpi>0)),
         salmon_cells = length(which(salmon_cpi>0))) %>% 
  mutate(prop_broiler = broiler_cells/ncells) %>% 
  filter(!is.na(iso3c) == T) %>% 
  full_join(., iso3_salmon_cpi) %>% 
  rename(salmon_cpi = country_farm_feed_chi) %>% 
  dplyr::select(-animal_system) %>% 
  full_join(., iso3_broiler_cpi) %>% 
  rename(chicken_cpi = country_farm_feed_chi) %>% 
  dplyr::select(-animal_system) %>% 
  mutate(broiler_cpi_cell = chicken_cpi/broiler_cells,
         salmon_cpi_cell = salmon_cpi/salmon_cells) %>% 
  full_join(., broiler_prod) %>% 
  full_join(., salmon_prod, by = c("Country" = "country", "iso3c"))

chicken_cells_iso3_cpi<-cells_iso3_cpi %>% 
  dplyr::select(-salmon_cpi,-salmon_cells, -salmon_cpi_cell)

write.csv(cells_iso3_cpi, here("_analysis/output_data/CPI_cells_by_country.csv"))
write.csv(test, here("_analysis/output_data/CPI_cells_by_country_top95perc.csv"))
```


# Chicken

Chicken CPI vs CPI footprint

```{r}
sub_dat<-test %>% 
  dplyr::select(iso3c, Country, broiler_cells, chicken_cpi, prop_broiler) %>% 
  mutate(broiler_cpi_pixel_lab = ifelse(broiler_cells>50000 | chicken_cpi > 0.1, as.character(Country), "Zoom"))

```

```{r}
sub_dat<- sub_dat %>% 
  filter(chicken_cpi>0,
         broiler_cells>0)

chick_cpi_km2_plot<-ggplot(sub_dat, aes(x = broiler_cells/100000, y = chicken_cpi, label = Country, col = prop_broiler)) + 
  #annotation_custom(chicken_png, xmin = -0.5, xmax = 1, ymin = 0.65, ymax=0.75) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_viridis_c(direction = -1) +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel(max.overlaps = 8) + 
  theme_bw() +
  xlab("Pixels (hundred thousands, log)") +
  ylab("") +
  labs(color = "Prop. of country cells")

chick_cpi_km2_plot
```

```{r}
ggsave(here("_analysis/figures/Chicken_cpi_km2_log10.png"), dpi = 300, height = 4, width = 10)
```

# Salmon

Salmon CPI per footprint

```{r}
sub_dat_salmon<-test %>% 
  filter(salmon_cpi>0,
         salmon_cells>0) %>% 
  dplyr::select(iso3c, Country, salmon_cells, salmon_cpi, prop_salmon) %>% 
  mutate(salmon_cpi_pixel_lab = ifelse(salmon_cells>100000 | salmon_cpi > 0.005, as.character(Country), 
                                       ifelse(salmon_cells<20, as.character(Country), NA))) %>% 
  mutate(salmon_cpi/salmon_cells)

salmon_cpi_km2_plot<-ggplot(sub_dat_salmon, aes(x = salmon_cells/100000, y = salmon_cpi, label = salmon_cpi_pixel_lab, color = prop_salmon)) +
 # annotation_custom(salmon_png, xmin = 0, xmax = 0.35, ymin = 0.035, ymax=0.045) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  geom_text_repel(max.overlaps= 20) +
  scale_color_viridis_c(direction = -1) +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
 # geom_text_repel(max.overlaps = 7, 
#                  force = 1) + 
  theme_bw() +
  xlab("Pixels (hundred thousands, log)") +
  ylab("") 

salmon_cpi_km2_plot
```


```{r}
ggsave(here("_analysis/figures/Salmon_cpi_km2_log10.png"),dpi = 300, height = 4, width = 10)
```

