---
title: "Maps of stresors"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

library(raster)
library(tidyverse)
library(sf)
library("rnaturalearth")

gall_peters <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

water <- readOGR(dsn=here("_analysis/raw/rgn_all_gcs_med_res.shp"))
water <- water[!water$rgn_nam == "Antarctica",]
proj4string(water) <- CRS("+proj=longlat +datum=WGS84")
water <- spTransform(water, CRS("+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))
plot(water)

land <- ne_countries(scale = "medium", returnclass = "sp") 
land <- land[!land$sov_a3 == "ATA",]
land <- st_as_sf(land)
land <- st_transform(land, crs=gall_peters)
land <- as(land, "Spatial")
plot(land)

library(RColorBrewer)
display.brewer.all()

stressor_df <- data.frame(stressor = c("ghg", "water", "nutrient", "disturbance"),
                          stressor_unit = c("CO2eq_tonnes", "m3", "PO4eq_tonnes", "proportion"))

```

## Cumulative stressors all food systems (only chickens and salmon at this point)
```{r}

# chi
chi_files <- raster("/home/shares/food-systems/Food_footprint/stressor_summary/equal_area/rescaled/cumulative_stress/cumulative_stress.tif")


chi_cols <- brewer.pal(9, "YlOrBr")[4:9]
chi_cols = colorRampPalette(chi_cols)(10000) 
chi_cols = c("NA", paste0(chi_cols, "BF"))
              
raster_data=chi_files
title="" 
cols=chi_cols

png(here(sprintf("_analysis/figures/maps/all_cumulative.png", system)), res=500, width=6, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
plot(water, border="#f2f8fc", col="#f2f8fc", lwd=0.5, main=sprintf("Total cumulative stress", system), cex=0.75)
plot(land, border="#c5b89c", col="#f6f2e9", lwd=0.5, add=TRUE)
plot(raster_data, 
     col=cols, 
     axes=FALSE, 
     box=FALSE, 
     add=TRUE,  
     legend=TRUE, 
     legend.shrink= 0.7, 
     legend.width=.4, 
     axis.args = list(cex.axis = 0.6, cex.sub=0.6, cex=0.6, lwd.ticks=1), 
     legend.args=list(text = "", cex = 0.75, side = 3, line = 1))

dev.off()

```



## Cumulative salmon and chicken

```{r}


chi_plot_system <- function(system="broiler"){
#system="salmon"

## get the max value
# chi
chi_all <- raster("/home/shares/food-systems/Food_footprint/stressor_summary/equal_area/rescaled/cumulative_stress/cumulative_stress.tif")/1000000

chi_all_quantile <- quantile(chi_all, 0.9999)
  
chi <- raster(list.files("/home/shares/food-systems/Food_footprint/stressor_summary/equal_area/rescaled/cumulative_stress", pattern = system, full=TRUE))/1000000

chi_cols <- brewer.pal(9, "YlOrBr")[4:9]
chi_cols = colorRampPalette(chi_cols)(10000) 
chi_cols = c("NA", paste0(chi_cols, "BF"))

chi[chi > chi_all_quantile] <- chi_all_quantile

              
#chi[chi > chi_all_quantile] <- quant 

raster_data=chi
title="" 
cols=chi_cols

png(here(sprintf("_analysis/figures/maps/%s_cumulative.png", system)), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
#cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4)

plot(water, border="#f2f8fc", col="#f2f8fc", lwd=0.5, main=sprintf("%s: cumulative stress", system), cex=0.75)
plot(land, border="#c5b89c", col="#f6f2e9", lwd=0.5, add=TRUE)
plot(raster_data, 
     breaks=seq(0, chi_all_quantile, length.out=10000),
     col=cols, 
     axes=FALSE, 
     box=FALSE, 
     add=TRUE,  
     legend=TRUE, 
     legend.shrink= 0.7, 
     legend.width=.4, 
     axis.args = list(cex.axis = 0.6, cex.sub=0.6, cex=0.6, lwd.ticks=1, at = c(0,0.00002,0.00004,round(chi_all_quantile, 6)),
                      labels=c("0", "0.00002", "0.00004", paste0(">", round(chi_all_quantile, 6)))), 
     legend.args=list(text = "", cex = 0.7, side = 3, line = 1))

dev.off()
}
  
chi_plot_system(system="broiler")
chi_plot_system(system="salmon")

```


#### NEED to UPDATE FOLLOWING


## Stressors, per km2
```{r}

system_stress_plot <- function(system="broiler", stressor = "ghg"){
#  system="broiler"
#  stressor = "ghg"
stressor_file <- raster(sprintf("/home/shares/food-systems/Food_footprint/stressor_summary/system_stressor/equal_area/%s_%s_per_area.tif", system, stressor))

quant <- quantile(stressor_file, c(0.999))
stressor_file[stressor_file > quant] <- quant 
  
chi_cols <- brewer.pal(9, "YlOrBr")[4:9]
chi_cols = colorRampPalette(chi_cols)(1000) 
chi_cols = c("NA", paste0(chi_cols, "BF"))
              
raster_data=stressor_file
title="" 
cols=chi_cols

png(here(sprintf("_analysis/figures/maps/%s_%s_per_km2.png", system, stressor)), res=500, width=6, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
plot(water, border="#f2f8fc", col="#f2f8fc", lwd=0.5, main=sprintf("%s: %s", system, stressor), cex=0.75)
plot(land, border="#c5b89c", col="#f6f2e9", lwd=0.5, add=TRUE)
plot(raster_data, 
     col=cols, 
     axes=FALSE, 
     box=FALSE, 
     add=TRUE,  
     legend=TRUE, 
     legend.shrink= 0.7, 
     legend.width=.4, 
     axis.args = list(cex.axis = 0.6, cex.sub=0.6, cex=0.6, lwd.ticks=1), 
     legend.args=list(text = "", cex = 0.75, side = 3, line = 1))

dev.off()
}
  
system_stress_plot(system="broiler", stressor = "ghg")
system_stress_plot(system="broiler", stressor = "water")
system_stress_plot(system="broiler", stressor = "nutrient")
system_stress_plot(system="broiler", stressor = "disturbance")

system_stress_plot(system="salmon", stressor = "ghg")
system_stress_plot(system="salmon", stressor = "water")
system_stress_plot(system="salmon", stressor = "nutrient")
system_stress_plot(system="salmon", stressor = "disturbance")

```


## Stressors, rescaled
```{r}

system_stress_plot <- function(system="broiler", stressor = "ghg"){
#  system="broiler"
#  stressor = "ghg"
stressor_file <- raster(sprintf("/home/shares/food-systems/Food_footprint/stressor_summary/rescaled/system_stressor/%s_%s_rescaled_w_total_chi.tif", system, stressor))

chi_cols <- brewer.pal(9, "YlOrBr")[4:9]
chi_cols = colorRampPalette(chi_cols)(1000) 
chi_cols = c("NA", paste0(chi_cols, "BF"))
              
raster_data=stressor_file
title="" 
cols=chi_cols

png(here(sprintf("_analysis/figures/maps/%s_%s_rescaled.png", system, stressor)), res=500, width=7, height=3, units="in")

par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
  
plot(water, border="#f2f8fc", col="#f2f8fc", lwd=0.5, main=sprintf("%s: %s", system, stressor), cex=0.75)
plot(land, border="#c5b89c", col="#f6f2e9", lwd=0.5, add=TRUE)
plot(raster_data, 
     breaks=seq(0,1,length.out=1000),
     col=cols, 
     axes=FALSE, 
     box=FALSE, 
     add=TRUE,  
     legend=TRUE, 
     legend.shrink= 0.7, 
     legend.width=.4, 
     axis.args = list(cex.axis = 0.6, cex.sub=0.6, cex=0.6, lwd.ticks=1, at = c(0,0.25, 0.5, 0.75,1)), 
     legend.args=list(text = "", cex = 0.75, side = 3, line = 1))

dev.off()
}
  
system_stress_plot(system="broiler", stressor = "ghg")
system_stress_plot(system="broiler", stressor = "water")
system_stress_plot(system="broiler", stressor = "nutrient")
system_stress_plot(system="broiler", stressor = "disturbance")

system_stress_plot(system="salmon", stressor = "ghg")
system_stress_plot(system="salmon", stressor = "water")
system_stress_plot(system="salmon", stressor = "nutrient")
system_stress_plot(system="salmon", stressor = "disturbance")

```


## farm vs. farm/feed
```{r}

# system <- "broiler"
# chi <- raster(list.files("/home/shares/food-systems/Food_footprint/stressor_summary/rescaled/cumulative_stress", pattern = system, full=TRUE))
# 
# farm <- list.files("/home/shares/food-systems/Food_footprint/stressor_summary/rescaled/feed_farm_system_stressor", pattern="farm", full=TRUE)
# farm <- grep("broiler", farm, value=TRUE)
# farm_stack <- stack(farm)
# farm_cum_stress <- sum(farm_stack, na.rm=TRUE)
# farm_cum_stress[farm_cum_stress==0] <- NA
# plot(farm_cum_stress)
# farm_cum_points <- rasterToPoints(farm_cum_stress, spatial=TRUE)
# 
# chi_cols <- brewer.pal(9, "YlOrBr")[4:9]
# chi_cols <-  colorRampPalette(chi_cols)(100) 
# chi_cols <-  c("NA", paste0(chi_cols, "BF"))
#               
# farm_cols <- brewer.pal(9, "RdYlGn")[6:9]
# farm_cols <- colorRampPalette(farm_cols)(100)
# farm_trans <- rep(c("1A", "33", "4D", "66", "99", "B3", "CC", "E6", "E6","FF"), each=10)
# farm_cols <- c(paste0(farm_cols, farm_trans))
# 
# raster_data=chi
# title="" 
# cols=chi_cols
# 
# png(here(sprintf("_analysis/figures/maps/%s_cumulative.png", system)), res=500, width=6, height=3, units="in")
# 
# par(oma=c(1,1,1,0), new = TRUE) # bottom, left, top, and right
# par(mfrow=c(1, 1), mar=c(1, 0, 1, 2))
#   
# plot(water, border="#f2f8fc", col="#f2f8fc", lwd=0.5, main=sprintf("%s: cumulative stress", system), cex=0.75)
# plot(land, border="#c5b89c", col="#f6f2e9", lwd=0.5, add=TRUE)
# plot(raster_data, 
#      col=cols, 
#      axes=FALSE, 
#      box=FALSE, 
#      add=TRUE,  
#      legend=FALSE, 
#      legend.shrink= 0.7, 
#      legend.width=.4, 
#      axis.args = list(cex.axis = 0.6, cex.sub=0.6, cex=0.6, lwd.ticks=1), 
#      legend.args=list(text = "", cex = 0.75, side = 3, line = 1))
# 
# plot(farm_cum_stress, col=farm_cols, pch=".", cex=0.000000001)
# 
# dev.off()

```