---
title: "Untitled"
author: "Caitie"
date: '2022-04-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(patchwork)
library(tidyverse)
library(ggrepel)
library(ggpmisc)
library(ggforce)
library(here)

options(scipen = 0)
```

```{r}
chicken<-read.csv(here("_analysis/output_data/Broiler_farm_cpi_prod.csv"))

salmon<-read.csv(here("_analysis/output_data/Salmon_farm_cpi_prod.csv"))
```



```{r}
chicken<-chicken %>% 
  filter(broiler_slaughter_wt_tonnes>0,
         cpi_prod>0)

chick_cpi_prod_plot<-ggplot(chicken, aes(x = broiler_slaughter_wt_tonnes/1000000, y = cpi_prod, label = Country)) + 
  #annotation_custom(chicken_png, xmin = -0.5, xmax = 1, ymin = 0.65, ymax=0.75) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel(max.overlaps = 5,
                  force = 1) + 
  theme_bw() +
  xlab("Production (million tonnes, log)") +
  ylab("On-farm CPI per tonne production (log)") #+
 # coord_trans("log10")

chick_cpi_prod_plot
```
```{r}
ggsave(here("_analysis/figures/Figure3a_Chicken_on_farm_efficiency_log10.png"), dpi = 300, height = 4, width = 6)
```

```{r}
salmon_cpi_prod_plot<-ggplot(salmon, aes(x = fao_tonnes_production/1000000, y = cpi_prod, label = Country)) + 
  #annotation_custom(chicken_png, xmin = -0.5, xmax = 1, ymin = 0.65, ymax=0.75) +
  geom_point() +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel(max.overlaps = 30) + 
  theme_bw() +
  scale_x_log10() +
  scale_y_log10() +
  xlab("Production (million tonnes, log)") +
  ylab("On-farm CPI per tonne production (log)") 

salmon_cpi_prod_plot
```

```{r}
ggsave(here("_analysis/figures/Figure3b_Salmon_on_farm_efficiency_log10.png"), dpi = 300, height = 4, width = 6) #width was 10
```

# Feed

```{r}
chicken_feed_prod<-read.csv(here("_analysis/output_data/Broiler_feed_cpi_prod.csv"))

salmon_feed_prod<-read.csv(here("_analysis/output_data/Salmon_feed_cpi_prod.csv"))
```


```{r}
chicken_feed_prod<-chicken_feed_prod %>% 
  mutate(country = ifelse(country == "Palestina", "Palestine", as.character(country)))

chick_feed_cpi_prod_plot<-ggplot(chicken_feed_prod, aes(x = feed_tonnes/1000000, y = cpi_per_tonne, label = country)) + 
  #annotation_custom(chicken_png, xmin = -0.5, xmax = 1, ymin = 0.65, ymax=0.75) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()+
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel(max.overlaps = 14) + 
  theme_bw() +
  xlab("Feed production (million tonnes, log)") +
  ylab("Feed CPI per tonne feed production (log)")

chick_feed_cpi_prod_plot
```
```{r}
ggsave(here("_analysis/figures/Figure3c_Chicken_feed_efficiency_log10.png"), dpi = 300, height = 4, width = 6)
```



```{r}
salmon_feed_prod<-salmon_feed_prod %>% 
  mutate(country = ifelse(country == "Palestina", "Palestine", as.character(country)))

salmon_feed_cpi_prod_plot<-ggplot(salmon_feed_prod, aes(x = feed_tonnes/1000000, y = cpi_per_tonne, label = country)) + 
  #annotation_custom(chicken_png, xmin = -0.5, xmax = 1, ymin = 0.65, ymax=0.75) +
  geom_point() +
  scale_x_log10()+
  scale_y_log10() +
  #geom_smooth(method = "lm", se=FALSE, color="lightblue", formula = my.formula) +
  #stat_poly_eq(formula = my.formula, 
  #              aes(label = paste(..rr.label.., sep = "~~~")), 
  #              parse = TRUE) +
  geom_text_repel(max.overlaps = 7) + 
  theme_bw() +
  xlab("Feed production (million tonnes, log)") +
  ylab("Feed CPI per tonne feed production (log)")

salmon_feed_cpi_prod_plot
```
```{r}
ggsave(here("_analysis/figures/Figure3d_Salmon_feed_efficiency_log10.png"), dpi = 300, height = 4, width = 6)
```


