---
title: "Raster extract"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

library(raster)
library(tidyverse)
library(sf)
library(RColorBrewer)
library(here)

```



## Summed stressors for each region

Use land/eez raster to extract the summed pressures on land in eez areas.

```{r}

rgns <- raster("/home/shares/food-systems/Food_footprint/all_food_systems/dataprep/spatial/land_eez_rgns.tif")
#plot(rgns)

rgn_names <- read_csv("/home/shares/food-systems/Food_footprint/chicken_salmon/_spatial/master_rgns.csv") %>%
  rename(land_area_km2 = area_km2)

eez_rgns <- read_csv("/home/shares/food-systems/Food_footprint/chicken_salmon/_spatial/eez_rgns.csv") %>%
  rename(eez_area_km2 = area_km2)

rescaling_values <- read_csv(here("_analysis/rescale_values.csv")) 
```



Zonal sum of land-based rasters:

```{r}
crops <- list.files("/home/shares/food-systems/Food_footprint/chicken_salmon/_tif_equal_area_proj_per_cell", pattern="feedcrop",
           full=TRUE)

broiler_farms <- list.files("/home/shares/food-systems/Food_footprint/chicken_salmon/_tif_equal_area_proj_per_cell",
                            pattern = "farm_land_chickens", full=TRUE)

land_based <- c(crops, broiler_farms)
land_stack <- stack(land_based)

```

```{r}
rgns_proj2<-projectRaster(rgns, land_stack, method="ngb")

```

```{r}
land_data <- zonal(land_stack, rgns_proj2, fun="sum", progress="text", na.rm=TRUE)

land_data_df <- data.frame(land_data) %>%
  rename(ID_0 = zone) %>%
 # left_join(rgn_names, by="ID_0") %>%
 # tidyr::pivot_longer(-c(ID_0, iso3c, Country), names_to = "source", values_to = "value") %>%  
  tidyr::pivot_longer(-c(ID_0), names_to = "source", values_to = "value") %>%
  mutate(source = gsub("gall_peter_","",as.character(source))) %>% 
  separate(source, sep="_", into=c("source", "subsource", "animal_system", "type", "type2", "stressor")) %>%
  mutate(stressor = ifelse(is.na(stressor), animal_system, stressor)) %>%
  mutate(animal_system = ifelse(animal_system==stressor, NA, animal_system)) %>%
  mutate(animal_system = ifelse(is.na(animal_system), subsource, animal_system)) %>%
    mutate(subsource = ifelse(animal_system==subsource, NA, subsource)) %>%
  mutate(location = "land")

  
```


Zonal sum of marine-based rasters:

```{r}

fisheries <- list.files("/home/shares/food-systems/Food_footprint/chicken_salmon/_tif_equal_area_proj_per_cell", pattern="feedfofm",
           full=TRUE)

salmon_farms <- list.files("/home/shares/food-systems/Food_footprint/chicken_salmon/_tif_equal_area_proj_per_cell",
                            pattern = "farm_marine_salmon", full=TRUE)
marine_based <- c(fisheries, salmon_farms)
marine_stack <- stack(marine_based)

marine_data <- zonal(marine_stack, rgns_proj2, fun="sum", progress="text", na.rm=TRUE)

marine_data_df <- data.frame(marine_data) %>%
  rename(ID_0 = zone) %>%
#  left_join(rgn_names, by="ID_0") %>%
#  tidyr::pivot_longer(-c(ID_0, iso3c, Country), names_to = "source", values_to = "value") %>%
    tidyr::pivot_longer(-c(ID_0), names_to = "source", values_to = "value") %>%
   mutate(source = gsub("gall_peter_","",as.character(source))) %>% 
  separate(source, sep="_", into=c("source", "subsource", "animal_system", "type", "type2", "stressor")) %>%
  mutate(stressor = ifelse(is.na(stressor), animal_system, stressor)) %>%
  mutate(animal_system = ifelse(animal_system==stressor, NA, animal_system)) %>%
  mutate(animal_system = ifelse(is.na(animal_system), subsource, animal_system)) %>%
    mutate(subsource = ifelse(animal_system==subsource, NA, subsource)) %>%
  mutate(location = "marine")
  

```

combine data
```{r}

all_data <- rbind(marine_data_df, land_data_df) %>%
  left_join(rgn_names) %>%
  left_join(eez_rgns)


write_csv(all_data, here("_analysis/output_data/sum_pressures_country.csv"))
```

