---
title: "summed_stressor"
author: "Juliette"
date: "4/20/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

This markdown calculates rasters for 

1. sum of each stressor by system (saved on Aurora: stressor_summary/equal_area/system_stressor)
2. sum of each stressor across all systems (saved on Aurora: stressor_summary/equal_area/stressor)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# sum each pressure for each food system

```{r}
# function

system_sum <- function(system){ #system="broiler"

stressor_list <- c("ghg", "water", "nutrient", "disturbance")

for(stressor in stressor_list){
#stressor <- "ghg"
stressor_files <- list.files("/home/shares/food-systems/Food_footprint/stressor_summary/equal_area/feed_farm_system_stressor", 
           pattern=stressor,
           full=TRUE)
stressor_files <- grep(system, stressor_files, value=TRUE)

stressor_stack <- stack(stressor_files)
stressor_sum <- sum(stressor_stack, na.rm=TRUE)
#plot(log(stressor_sum + 1))
writeRaster(stressor_sum, sprintf("/home/shares/food-systems/Food_footprint/stressor_summary/equal_area/system_stressor/%s_%s_per_cell.tif", system, stressor), overwrite=TRUE)
}
}
```

```{r}

system_sum(system="broiler")
system_sum(system="salmon")

```

# Each stressor: cumulative
For each stressor get sum of all inputs across all systems.
```{r}

stressor_list <- c("ghg", "water", "nutrient", "disturbance")

for(stressor in stressor_list){
#stressor <- "ghg"
  
  stressor_files <- list.files("/home/shares/food-systems/Food_footprint/stressor_summary/equal_area/feed_farm_system_stressor", pattern=stressor,
           full=TRUE)

stressor_stack <- stack(stressor_files)
stressor_sum <- sum(stressor_stack, na.rm=TRUE)
#plot(log(stressor_sum + 1))
writeRaster(stressor_sum, sprintf("/home/shares/food-systems/Food_footprint/stressor_summary/equal_area/stressor/%s_per_cell.tif", 
                                  stressor), 
            overwrite=TRUE)
}

```

