---
title: "Step_2_raster_create_equal_area_proj"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(rgdal)
library(sp)
library(raster)
library(tidyverse)
library(here)

gall_peters <- "+proj=cea +lon_0=0 +x_0=0 +y_0=0 +lat_ts=45 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

#raster template 
template_eq_area <- raster(res=0.083333333333333333)
extent(template_eq_area) <- c(-180, 180, -90, 90)
template_eq_area <- projectRaster(template_eq_area, crs=gall_peters, res=3000) 


```

## convert to equal area gall peters

```{r}

rasters <- list.files(file.path("/home/shares/food-systems/Food_footprint/final_data/_tif_version_per_km2"), full=TRUE)

for(rast in rasters){ # rast <- rasters[1]
  
rast_name <- basename(rast)
 getraster <- raster(rast)
 highres_raster <- disaggregate(getraster, fact=2)

 projectRaster(highres_raster, template_eq_area, method="ngb", over=TRUE, progress="text",
                       filename=sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km2/hi_res_gall_peter_%s", rast_name), overwrite=TRUE)

gp_raster <- raster(sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km2/hi_res_gall_peter_%s", rast_name))

aggregate(gp_raster, fact=2, fun=mean, filename=sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km/gall_peter_%s", rast_name), overwrite=TRUE)

}

```

Do the consumption rasters as well.
```{r}

rasters <- list.files(file.path("/home/shares/food-systems/Food_footprint/final_data/_tif_version_per_cell"), full=TRUE, pattern="consumption")

for(rast in rasters){ # rast <- rasters[1]
  
rast_name <- basename(rast)
 getraster <- raster(rast)
 highres_raster <- disaggregate(getraster, fact=2)

 projectRaster(highres_raster, template_eq_area, method="ngb", over=TRUE, progress="text",
                       filename=sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km2/hi_res_gall_peter_%s", rast_name), overwrite=TRUE)

gp_raster <- raster(sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km/hi_res_gall_peter_%s", rast_name))

aggregate(gp_raster, fact=2, fun=mean, filename=sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km/gall_peter_%s", rast_name), overwrite=TRUE)

}

```


Delete the hi_res version which is just a temp file.
```{r}
remove <- list.files(file.path("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km2"), full=TRUE, pattern="hi_res")
file.remove(remove)
```

Check that all went well. Compare raw rasters to the values here. These should basically match, but there will be some error due to estimates relating to altering the projection.
```{r}
rasters <- list.files(file.path("/home/shares/food-systems/Food_footprint/final_data/_tif_version_per_cell"), full=TRUE)
rasters <- grep("_consumption", rasters, value=TRUE, invert=TRUE)

check_data <- data.frame()
for(rast in rasters){ # rast=rasters[1]
  file_name <- basename(rast)
  file_name <- gsub(".tif", "", file_name)
  org_raster <- raster(rast)
  org_data <- cellStats(org_raster, "sum", na.rm=TRUE)
  
  new_raster_path <- grep(file_name, list.files("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km2", full=TRUE), value=TRUE)
  new_raster <- raster(new_raster_path)
  new_data_pre <- new_raster*area(new_raster)/1000000
  new_data <- cellStats(new_data_pre, "sum", na.rm=TRUE)
  new_dataframe <- data.frame(name=file_name, org_data=org_data, new_data=new_data)
  check_data <- rbind(check_data, new_dataframe)
}

plot(log(check_data$org_data +1), log(check_data$new_data +1))
abline(0,1, col="red")

check_data_compare <- check_data %>%
  mutate(percent = org_data/new_data)

hist(check_data_compare$percent)
```

## convert to total per cell
```{r}

per_km_rasts <- list.files("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_km2", full=TRUE)
per_km_rasts <- grep("consumption", per_km_rasts, value=TRUE, invert=TRUE)

for(rast in per_km_rasts){ # rast = per_km_rasts[1]
 save_name <- basename(rast)
 save_name <- gsub("_per_area", "_per_cell", save_name)
    new_raster <- raster(rast)
  per_cell_rast <- new_raster*area(new_raster)/1000000
writeRaster(per_cell_rast, sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_cell/%s", save_name), overwrite=TRUE)

#check <- raster(sprintf("/home/shares/food-systems/Food_footprint/final_data/_tif_equal_area_proj_per_cell/%s", save_name))
#cellStats(check, "sum", na.rm=TRUE)
}

```